bridge_domains:
- bd_name: 172.16.1.0_BD
  tenant: demo
  vrf: PROD
  subnet_name: 172.16.1.0_BD
  gateway: 172.16.1.1
  mask: 24
  scope: public
  description: something
  bd_type: ethernet
  mac_address: 00:22:BD:F8:19:FF
  l2_unknown_unicast: proxy
  l3_unknown_multicast: flood
  ipv6_l3_unknown_multicast: flood
  multi_dest: bd-flood
  arp_flooding: false
  enable_routing: true
  ip_learning: true
  enable_multicast: false
  state: present
