---
bridge_domains:
-   bd_name: 172.16.1.0_BD
    tenant: demo
    vrf: PROD
    subnet_name: 172.16.1.0_BD
    gateway: 172.16.1.1
    mask: '24'
    scope: public
    description: Bridge Domain for Applications in VLAN 10
    bd_type: ethernet
    mac_address: 00:22:BD:F8:19:FF
    l2_unknown_unicast: proxy # ["flood","proxy"]
    l3_unknown_multicast: flood # ["flood","opt-flood"]
    ipv6_l3_unknown_multicast: flood # ["flood","opt-flood"]
    multi_dest: bd-flood # ["bd-flood", "drop", "encap-flood"]
    arp_flooding: true
    enable_routing: true
    ip_learning: true
    enable_multicast: false
    state: present
    l3out: BGP_L3Out # Apply L3out variable to bind this BD to an L3Out

-   bd_name: 172.16.2.0_BD
    tenant: demo
    vrf: PROD
    scope: public
    description: Bridge Domain for Applications in VLAN 20
    bd_type: ethernet
    mac_address: 00:22:BD:F8:19:FF
    l2_unknown_unicast: proxy # ["flood","proxy"]
    l3_unknown_multicast: flood # ["flood","opt-flood"]
    ipv6_l3_unknown_multicast: flood # ["flood","opt-flood"]
    multi_dest: bd-flood # ["bd-flood", "drop", "encap-flood"]
    arp_flooding: false
    enable_routing: true
    ip_learning: true
    enable_multicast: false
    state: present

-   bd_name: L2Out_BD
    tenant: demo
    vrf: PROD
    scope: public
    description: Bridge Domain for L2Out
    bd_type: ethernet
    mac_address: 00:22:BD:F8:19:FF
    l2_unknown_unicast: flood # ["flood","proxy"]
    l3_unknown_multicast: flood # ["flood","opt-flood"]
    ipv6_l3_unknown_multicast: flood # ["flood","opt-flood"]
    multi_dest: bd-flood # ["bd-flood", "drop", "encap-flood"]
    arp_flooding: true
    enable_routing: false
    ip_learning: true
    enable_multicast: false
    state: present