---
tenant: demo
contracts:
  - contract: Web-App
    subject: subject1
    filter: http
    scope: context # (application-profile, global, tenant)
    state: present
  - contract: Web-App
    subject: subject2
    filter: icmp
    scope: context # (application-profile, global, tenant)
    state: present
  - contract: Cache
    subject: subject1
    filter: cache
    scope: context # (application-profile, global, tenant)
    state: present
  - contract: Cache
    subject: subject2
    filter: icmp
    scope: context # (application-profile, global, tenant)
    state: present
  - contract: SQL
    subject: subject1
    filter: sql
    scope: context # (application-profile, global, tenant)
    state: present
  - contract: SQL
    subject: subject2
    filter: icmp
    scope: context # (application-profile, global, tenant)
    state: present
filters:
  - filter: sql
    entry: sql
    ether_type: ip
    protocol: tcp
    port: 3306
    description: Filter traffic destined to SQL
  - filter: http
    entry: http
    ether_type: ip
    protocol: tcp
    port: 8080
    description: Filter traffic destined to Web server HTTP
  - filter: icmp
    entry: icmp
    ether_type: ip
    protocol: icmp
    port: 0
    description: Filter traffic destined to ICMP
  - filter: cache
    entry: cache
    ether_type: ip
    protocol: tcp
    port: 6379
    description: Filter traffic destined to caching port
epg_contracts:
  - epg: EPG_Web1
    ap_name: App1_Network_Segments
    contract: Web-App
    type: consumer
  - epg: EPG_Web1
    ap_name: App1_Network_Segments
    contract: default
    type: consumer
  - epg: EPG_App1
    ap_name: App1_Network_Segments
    contract: SQL
    type: consumer
  - epg: EPG_App1
    ap_name: App1_Network_Segments
    contract: Web-App
    type: provider
  - epg: EPG_App1
    ap_name: App1_Network_Segments
    contract: Cache
    type: consumer
  - epg: EPG_DB1
    ap_name: App1_Network_Segments
    contract: SQL
    type: provider
  - epg: EPG_DB1
    ap_name: App1_Network_Segments
    contract: Cache
    type: provider
extepg_contracts:
  - extepg: Ext_EPG
    l3out: OSPF_L3Out
    contract: default
    contract_type: provider
    state: present
