---
demo_tenant: demo
contracts:
  - contract: ANY
    subject: Permit_Any
    filter: ip_any
    scope: context # (application-profile, global, tenant)
    description: Permit all traffic 
    state: present
  - contract: L3Out_contract
    subject: Permit_Any
    filter: ip_any
    scope: context # (application-profile, global, tenant)
    description: Permit all traffic 
    state: present

filters:
  - filter_name: ip_any
    entry_name: ip_any
    ether_type: ip
    protocol: unspecified
    port: unspecified
    description: Filter traffic to match any ip traffic
    state: present

extepg_contracts:
  - extepg: BGP_Ext_EPG
    l3out: BGP_L3Out
    contract: L3Out_contract
    contract_types:
      - provider
      - consumer
    state: present
