---
epgs:
  - epg_name: EPG_Web1
    ap_name: App1_Network_Segments
    tenant: demo
    description: EPG for web servers
    intra_epg_isolation: unenforced
    bd: 172.16.1.0_BD
    esg: App1_ESG
    aaep_list: 
      - Apps_AAEP
      - External_L2Net_AAEP
    vlan: 200
    interface_mode: trunk # access, native, trunk
    domain: demo_PhyDom
    domain_type: phys
    state: present

  - epg_name: EPG_App1
    ap_name: App1_Network_Segments
    tenant: demo
    description: EPG for App servers
    intra_epg_isolation: unenforced
    bd: 172.16.1.0_BD
    esg: App1_ESG
    aaep_list: 
      - Apps_AAEP
      - External_L2Net_AAEP
    vlan: 201
    interface_mode: trunk # access, native, trunk
    domain: demo_PhyDom
    domain_type: phys
    state: present

  - epg_name: EPG_DB1
    ap_name: App1_Network_Segments
    tenant: demo
    description: EPG for DB servers
    intra_epg_isolation: unenforced
    bd: 172.16.1.0_BD
    esg: App1_ESG
    aaep_list: 
      - Apps_AAEP
      - External_L2Net_AAEP
    vlan: 202
    interface_mode: trunk # access, native, trunk
    domain: demo_PhyDom
    domain_type: phys
    state: present

  - epg_name: EPG_Web2
    ap_name: App2_Network_Segments
    tenant: demo
    description: EPG for web servers
    intra_epg_isolation: unenforced
    bd: 172.16.2.0_BD
    esg: App2_ESG
    aaep_list: 
      - Apps_AAEP
      - External_L2Net_AAEP
    vlan: 203
    interface_mode: trunk # access, native, trunk
    domain: demo_PhyDom
    domain_type: phys
    state: present

  - epg_name: EPG_App2
    ap_name: App2_Network_Segments
    tenant: demo
    description: EPG for app servers
    intra_epg_isolation: unenforced
    bd: 172.16.2.0_BD
    esg: App2_ESG
    aaep_list: 
      - Apps_AAEP
      - External_L2Net_AAEP
    vlan: 204
    interface_mode: trunk # access, native, trunk
    domain: demo_PhyDom
    domain_type: phys
    state: present

  - epg_name: EPG_DB2
    ap_name: App2_Network_Segments
    tenant: demo
    description: EPG for web servers
    intra_epg_isolation: unenforced
    bd: 172.16.2.0_BD
    esg: App2_ESG
    aaep_list: 
      - Apps_AAEP
      - External_L2Net_AAEP
    vlan: 205
    interface_mode: trunk # access, native, trunk
    domain: demo_PhyDom
    domain_type: phys
    state: present
