---
tenant: mgmt
# ------------------------------ #
# INB BD, EPG, and static ip add #
# ------------------------------ #
inb_bridge_domain:
  - bd_name: inb
    subnet_name: inb
    gateway: 172.16.1.1
    mask: 24
    description: inb subnet
    scope: public
    l3out: INB_BGP_L3Out
    state: present

inb_epg:
  - epg_name: INB_EPG
    type: in_band
    vlan: vlan-350
    bd: inb
    state: present

inb_addresses:
  - node_id: 1
    pod_id: 1
    epg: INB_EPG
    ipv4_addr: 172.16.1.10/24
    ipv4_gw: 172.16.1.1
    state: present
  - node_id: 101
    pod_id: 1
    epg: INB_EPG
    ipv4_addr: 172.16.1.101/24
    ipv4_gw: 172.16.1.1
    state: present
  - node_id: 102
    pod_id: 1
    epg: INB_EPG
    ipv4_addr: 172.16.1.102/24
    ipv4_gw: 172.16.1.1
    state: present
  - node_id: 201
    pod_id: 1
    epg: INB_EPG
    ipv4_addr: 172.16.1.201/24
    ipv4_gw: 172.16.1.1
    state: present

# -------------- #
# L3 Out for INB #
# -------------- #

inb_bgp_l3out:
  - name: INB_BGP_L3Out
    vrf: inb
    domain: L3Out_Dom
    route_control: export
    protocol: bgp
    state: present

inb_bgp_l3out_node_profile:
  - profile: INB_BGP_L3Out_NodeProfile
    l3out: INB_BGP_L3Out
    state: present

inb_bgp_l3out_nodes:
  - profile: INB_BGP_L3Out_NodeProfile
    l3out: INB_BGP_L3Out
    pod_id: 1
    node_id: 101
    router_id: 101.101.101.101
    router_id_as_lo: false
    state: present
  - profile: INB_BGP_L3Out_NodeProfile
    l3out: INB_BGP_L3Out
    pod_id: 1
    node_id: 102
    router_id: 102.102.102.102
    router_id_as_lo: false
    state: present

inb_bgp_l3out_interface_profile:
  - profile: INB_BGP_L3Out_Interfaces
    node_profile: INB_BGP_L3Out_NodeProfile
    l3out: INB_BGP_L3Out
    state: present

inb_bgp_l3out_interfaces:
  - if_profile: INB_BGP_L3Out_Interfaces
    node_profile: INB_BGP_L3Out_NodeProfile
    l3out: INB_BGP_L3Out
    pod_id: 1
    node_id: 101
    if_path: eth1/21
    if_type: sub-interface # (l3-port, sub-interface, ext-svi)
    vlan: vlan-151
    addr: 10.10.10.9/30
    mtu: 1500
    bgp_peers:
      - peer_ip: 10.10.10.10
        remote_asn: 65010
        ttl: 5
        admin_state: enabled
        bgp_controls:
          - send-com
          - send-ext-com
    state: present
  - if_profile: INB_BGP_L3Out_Interfaces
    node_profile: INB_BGP_L3Out_NodeProfile
    l3out: INB_BGP_L3Out
    pod_id: 1
    node_id: 102
    if_path: eth1/21
    if_type: sub-interface # (l3-port, sub-interface, ext-svi)
    vlan: vlan-151
    addr: 10.10.10.13/30
    mtu: 1500
    bgp_peers:
      - peer_ip: 10.10.10.14
        remote_asn: 65010
        ttl: 5
        admin_state: enabled
        bgp_controls:
          - send-com
          - send-ext-com
    state: present

inb_bgp_extepg:
  - name: INB_BGP_Ext_EPG
    l3out: INB_BGP_L3Out
    subnet: 0.0.0.0/0
    subnet_scope: import-security
    state: present

# --------------------------------------------------------#
# Contract VARS to bind contract to INB EPG and L3Out EPG #
# --------------------------------------------------------#

inb_filters:
  - filter_name: ip_any
    entry_name: ip_any
    ether_type: ip
    protocol: unspecified
    port: unspecified
    description: Filter traffic to match any ip traffic
    state: present

inb_contracts:
  - contract: ANY
    subject: Permit_Any
    filter: ip_any
    scope: context # (application-profile, global, tenant)
    description: Permit all traffic 
    state: present

inb_extepg_contracts:
  - extepg: INB_BGP_Ext_EPG
    l3out: INB_BGP_L3Out
    contract: ANY
    contract_types:
      - provider
      - consumer
    state: present

