---
bgp_l3out:
  - name: BGP_L3Out
    tenant: demo
    vrf: PROD
    domain: L3Out_Dom
    route_control: export
    protocol: bgp
    state: present

bgp_l3out_node_profile:
  - profile: BGP_L3Out_Nodes
    tenant: demo
    l3out: BGP_L3Out
    state: present

bgp_l3out_nodes:
  - profile: BGP_L3Out_Nodes
    tenant: demo
    l3out: BGP_L3Out
    pod_id: 1
    node_id: 101
    router_id: 101.101.101.101
    router_id_as_lo: false
    state: present
  - profile: BGP_L3Out_Nodes
    tenant: demo
    l3out: BGP_L3Out
    pod_id: 1
    node_id: 102
    router_id: 102.102.102.102
    router_id_as_lo: false
    state: present

bgp_l3out_interface_profile:
  - profile: BGP_L3Out_Interfaces
    node_profile: BGP_L3Out_Nodes
    tenant: demo
    l3out: BGP_L3Out
    state: present

bgp_l3out_interfaces:
  - if_profile: BGP_L3Out_Interfaces
    node_profile: BGP_L3Out_Nodes
    tenant: demo
    l3out: BGP_L3Out
    pod_id: 1
    node_id: 101
    if_path: eth1/21
    if_type: sub-interface # (l3-port, sub-interface, ext-svi)
    vlan: vlan-149
    addr: 10.10.10.1/30
    mtu: 1500
    bgp_peers:
      - peer_ip: 10.10.10.2
        remote_asn: 65010
        ttl: 5
        admin_state: enabled
        bgp_controls:
          - send-com
          - send-ext-com
    state: present
  - if_profile: BGP_L3Out_Interfaces
    node_profile: BGP_L3Out_Nodes
    tenant: demo
    l3out: BGP_L3Out
    pod_id: 1
    node_id: 102
    if_path: eth1/21
    if_type: sub-interface # (l3-port, sub-interface, ext-svi)
    vlan: vlan-149
    addr: 10.10.10.5/30
    mtu: 1500
    bgp_peers:
      - peer_ip: 10.3.2.2
        remote_asn: 65010
        ttl: 5
        admin_state: enabled
        bgp_controls:
          - send-com
          - send-ext-com
    state: present

bgp_extepg:
  - name: BGP_Ext_EPG
    tenant: demo
    l3out: BGP_L3Out
    subnet: 0.0.0.0/0
    subnet_scope: import-security
    contract_name: ICMP
    contract_type: provider
    state: present
