--- 
l3out:
  - name: OSPF_L3Out
    tenant: demo
    vrf: PROD
    domain: L3Out_Dom
    route_control: export
    protocol: ospf 
    ospf_area_id: 0
    ospf_area_type: regular #(regular, nssa, stub)
    ospf_area_cost: 1
    state: present

l3out_node:
  - profile: OSPF_L3Out_Nodes
    tenant: demo
    l3out: OSPF_L3Out
    pod_id: 1
    node_id: 101
    router_id: 1.11.11.1
    router_id_as_lo: no
    state: present

l3out_interface:
  - profile: OSPF_L3Out_Interfaces
    node_profile: OSPF_L3Out_Nodes
    tenant: demo
    l3out: OSPF_L3Out
    pod_id: 1
    node_id: 101
    if_path: eth1/20
    if_type: l3-port # (l3-port, sub-interface, ext-svi)
    addr: 10.2.2.1/30
    mtu: 1500
    state: present

extepg:
  - name: Ext_EPG
    tenant: demo
    l3out: OSPF_L3Out
    subnet: 0.0.0.0/0
    subnet_scope: import-security
    contract_name: ICMP
    contract_type: provider
    state: present

ospf_if_policy:
  tenant: demo       # can be under common and reuse it everywhere
  l3out: OSPF_L3Out
  node_profile: OSPF_L3Out_Nodes
  interface_profile: OSPF_L3Out_Interfaces
  name: OSPF_Broadcast_Pol
  network_type: bcast    # p2p|bcast
  state: present