---
epg_bindings:
  - epg: EPG_Web1
    ap: App1_Network_Segments
    tenant: demo
    pod_id: 1
    leaf: '101'
    interface: 1/1
    interface_type: switch_port
    interface_mode: access
    encap_id: 101
    description: testing static path
    state: present
  - epg: EPG_App1
    ap: App1_Network_Segments
    tenant: demo
    pod_id: 1
    leaf: '101'
    interface: 1/2
    interface_type: switch_port
    interface_mode: access
    encap_id: 102
    description: testing static path
    state: present
  - epg: EPG_DB1
    ap: App1_Network_Segments
    tenant: demo
    pod_id: 1
    leaf: 101
    interface: 1/3
    interface_type: switch_port
    interface_mode: access
    encap_id: 103
    description: testing static path
    state: present
  - epg: EPG_Web2
    ap: App2_Network_Segments
    tenant: demo
    pod_id: 1
    leaf: 101-102
    interface: 'Cluster_VPC_IPG'
    interface_type: vpc
    interface_mode: trunk
    encap_id: 110
    description: testing static path
    state: absent
