---
# tasks file for roles/ap_int_policy
# create interface policies that will be attached to interface profiles

- name: Create Interface Policy for LLDP (lldp:IfPol)
  cisco.aci.aci_interface_policy_lldp:
    lldp_policy: "{{ item.name }}"
    description: "{{ item.description }}"
    receive_state: "{{ item.receive }}"
    transmit_state: "{{ item.transmit }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: interface_policy_lldp is defined
  loop: "{{ interface_policy_lldp }}"

- name: Create Interface Policy for CDP(cdp:IfPol)
  cisco.aci.aci_interface_policy_cdp:
    name: "{{ item.name }}"
    admin_state: "{{ item.admin_state }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: interface_policy_cdp is defined
  loop: "{{ interface_policy_cdp }}"

- name: Create Interface Policy for LACP(lacp:LagPol)
  cisco.aci.aci_interface_policy_port_channel:
    port_channel: "{{ item.name }}"
    description: "{{ item.description }}"
    min_links: "{{ item.min }}"
    max_links: "{{ item.max }}"
    mode: "{{ item.mode }}"
  delegate_to: localhost
  when: interface_policy_lacp is defined
  loop: "{{ interface_policy_lacp }}"

