---
- name: Create access policies
  hosts: fabric1
  gather_facts: false
  connection: local
  any_errors_fatal: true
  module_defaults:
    group/cisco.aci.all:
      hostname: "{{ ansible_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: "{{ apic_validate_certs }}"
      use_proxy: "{{ apic_use_proxy }}"
      output_path: "output/access_dryrun_data.json"

  roles:
    - ap_swp
    - ap_ifp
    - ap_int_policy
    - ap_access_ipg
    - ap_vpc_ipg
    - ap_vpc_prot_grp
    - ap_interface_selector
    - ap_vlans
    - ap_domains
    - ap_aaep
