---
- name: Test connectivity
  hosts: fabric1
  gather_facts: false
  connection: local
  any_errors_fatal: true
  module_defaults:
    group/cisco.aci.all:
      hostname: "{{ ansible_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: "{{ apic_validate_certs }}"
      use_proxy: "{{ apic_use_proxy }}"

  tasks:
    - name: Fetch APIC system info 
      cisco.aci.aci_rest:
        path: /api/node/class/topSystem.json
        method: get 
      register: apic_response

    - name: Show APIC hostname 
      debug:
        msg: "Connected to APIC, hostname is {{ apic_response.imdata[0].topSystem.attributes.name }}"