---
- name: Register Leaf and Spines (fabric:NodeIdentP)
  cisco.aci.aci_fabric_node:
    switch: "{{ item.switch_name }}"
    node_id: "{{ item.node_id }}"
    serial: "{{ item.serial }}"
    role: "{{ item.role }}"
    pod_id: "{{ item.pod_id }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: register_nodes_nodes is defined
  loop: "{{ register_nodes_nodes }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false

- name: Assign OOB addresses to nodes
  cisco.aci.aci_static_node_mgmt_address:
    epg: default
    pod_id: "{{ item.pod_id }}"
    type: out_of_band
    node_id: "{{ item.node_id }}"
    ipv4_address: "{{ item.ipv4_addr }}"
    ipv4_gw: "{{ item.ipv4_gw }}"
  delegate_to: localhost
  when: register_nodes_nodes is defined
  loop: "{{ register_nodes_nodes }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false