---
# tasks file for roles/ap-domains
- name: Read CSV information
  read_csv:
    path: host_vars/fabric1/access_policies/ap-domains.csv
  register: domains
  tags:
    - skip_ansible_lint

- name: Create/Ensure Domain  (L2dom, L3dom,phys)
  cisco.aci.aci_domain:
    domain: "{{ item.domain_name }}"
    domain_type: "{{ item.domain_type }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  loop: "{{ domains.list }}"
  when: domains is defined
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false

- name: Bind VLAN Pool to Domain  (infra:RsVlanNs)
  cisco.aci.aci_domain_to_vlan_pool:
    domain: "{{ item.domain_name }}"
    domain_type: "{{ item.domain_type }}"
    pool: "{{ item.vlan_pool }}"
    pool_allocation_mode: "{{ item.vlan_pool_allocation_mode }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  loop: "{{ domains.list }}"
  when: domains is defined
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false
