---
# tasks file for roles/ap-vlans

- name: Create VLAN Pool
  cisco.aci.aci_vlan_pool:
    pool: "{{ item.vlan_pool_name }}"
    pool_allocation_mode: "{{ item.vlan_pool_mode }}"
    description: "{{ item.vlan_pool_description }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  loop: "{{ vlan_pools }}"
  when: vlan_pools is defined
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false

- name: Create VLAN Pool Block
  cisco.aci.aci_vlan_pool_encap_block:
    pool: "{{ item.vlan_pool_name }}"
    pool_allocation_mode: "{{ item.vlan_pool_mode }}"
    block_start: "{{ item.start }}"
    block_end: "{{ item.end }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  loop: "{{ vlan_block_ranges }}"
  when: vlan_block_ranges is defined
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false
