---
- name: Create tenant policies for fabric1
  hosts: fabric1
  gather_facts: false
  connection: local
  any_errors_fatal: true
  module_defaults:
    group/cisco.aci.all:
      hostname: "{{ ansible_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: "{{ apic_validate_certs }}"
      use_proxy: "{{ apic_use_proxy }}"
      output_path: "{{ playbook_dir }}/tn_dryrun_data.json"

  roles:
    - tn_tenant
    - tn_vrf
    - tn_ap
    - tn_bd
    - tn_epg
    - tn_l3out
    - tn_contracts
