---
# tasks file for roles/ap_vpc_prot_grp

# This task loops through VPC pairs defined in the vars file ap-vpc-prot-grp.csv
# Applies the default vpc domain policy and gives the VPC protection group a Logical Pair id
- name: Read CSV information
  community.general.read_csv:
    path: ap-vpc-prot-grp.csv
  register: vpc_protection_group

- name: Create VPC Explicit Protection Group for VPC Pairs (fabric:ExplicitGEp and fabric:NodePEp)
  cisco.aci.aci_switch_policy_vpc_protection_group:
    protection_group: "{{ item.vpc_protection_group_name }}"
    protection_group_id: "{{ item.pg_id }}"
    switch_1_id: "{{ item.switch_1_id }}"
    switch_2_id: "{{ item.switch_2_id }}"
    vpc_domain_policy: "{{ item.domain_policy }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: vpc_protection_group is defined
  loop: "{{ vpc_protection_group.list }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false
