---
# tasks file for roles/tn_epg

- name: Create EPGs(fv:AEPg)
  cisco.aci.aci_epg:
    tenant: "{{  item.tenant }}"
    ap: "{{ item.ap_name }}"
    epg: "{{ item.epg_name }}"
    description: "{{ item.description }}"
    intra_epg_isolation: "{{ item.intra_epg_isolation }}"
    bd: "{{ item.bd }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: epgs is defined
  loop: "{{ epgs }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false
