---
# tasks file for roles/tn_epg

- name: Create EPGs(fv:AEPg)
  cisco.aci.aci_epg:
    tenant: "{{  item.tenant }}"
    ap: "{{ item.ap_name }}"
    epg: "{{ item.epg_name }}"
    description: "{{ item.description }}"
    intra_epg_isolation: "{{ item.intra_epg_isolation }}"
    bd: "{{ item.bd }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: epgs is defined
  loop: "{{ epgs }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false

- name: Bind EPG to AAEP (infra:RsFuncToEPG)
  cisco.aci.aci_aep_to_epg:
    epg: "{{ item.epg_name }}"
    aep: "{{ item.aaep }}"
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap_name }}"
    encap_id: "{{ item.vlan }}"
    interface_mode: "{{ item.interface_mode }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: epgs is defined
  loop: "{{ epgs }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false

- name: Bind EPG to Domain (fv:RsDomAtt)
  cisco.aci.aci_epg_to_domain:
    epg: "{{ item.epg_name }}"
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap_name }}"
    domain: "{{ item.domain }}"
    domain_type: "{{ item.domain_type }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: epgs is defined
  loop: "{{ epgs }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false
