aaeps:
  - aaep_name: Apps_AAEP
    aaep_description: AAEP for apps residing in cluster
    aaep_infra_vlan: 'FALSE'
    domain_name: demo_PhyDom
    domain_type: phys
    state: present
  - aaep_name: Mgmt_AAEP
    aaep_description: AAEP for mgmt services
    aaep_infra_vlan: 'FALSE'
    domain_name: demo_PhyDom
    domain_type: phys
    state: present
  - aaep_name: External_Net_AAEP
    aaep_description: AAEP for connection to ext networks
    aaep_infra_vlan: 'FALSE'
    domain_name: L3Out_Dom
    domain_type: l3dom
    state: present
  - aaep_name: External_L2Net_AAEP
    aaep_description: AAEP for connection to ext networks
    aaep_infra_vlan: 'FALSE'
    domain_name: demo_PhyDom
    domain_type: phys
    state: present
  - aaep_name: INB_AAEP
    aaep_description: AAEP for connection to ext networks
    aaep_infra_vlan: 'FALSE'
    domain_name: demo_PhyDom
    domain_type: phys
    state: present