---
interface_policy_lldp:
  - name: LLDP_Enabled
    description: Enable LLDP on interface 
    receive: yes
    transmit: yes
    state: present
  - name: LLDP_Disabled
    description: Disable LLDP on interface 
    receive: no
    transmit: no
    state: present
interface_policy_cdp:
  - name: CDP_Enabled
    admin_state: on
    state: present
  - name: CDP_Disabled
    admin_state: off
    state: present
interface_policy_lacp:
  - name: LACP_Active
    description: LACP Active 
    min: 1
    max: 16
    mode: active 
