---
interface_selector:
  - name: eth1_1
    description: 
    ifp: LEAF101_IFP
    interface_type: switch_port
    leaf_port_block: 1
    from: 1
    to: 1
    ipg: Baremetal_Server_IPG
    state: present

  - name: eth1_2
    description: 
    ifp: LEAF101_IFP
    interface_type: switch_port
    leaf_port_block: 1
    from: 2
    to: 2
    ipg: Baremetal_Server_IPG
    state: present

  - name: eth1_3
    description: 
    ifp: LEAF101_IFP
    interface_type: switch_port
    leaf_port_block: 1
    from: 3
    to: 3
    ipg: Baremetal_Server_IPG
    state: present

  - name: eth1_20
    description: 
    ifp: LEAF101_IFP
    interface_type: switch_port
    leaf_port_block: 1
    from: 20
    to: 20
    ipg: External_Catalyst_IPG
    state: present

  - name: eth1_21
    description: 
    ifp: LEAF101_IFP
    interface_type: switch_port
    leaf_port_block: 1
    from: 21
    to: 21
    ipg: External_Catalyst_IPG
    state: present

  - name: eth1_21
    description: 
    ifp: LEAF102_IFP
    interface_type: switch_port
    leaf_port_block: 1
    from: 21
    to: 21
    ipg: External_Catalyst_IPG
    state: present

  - name: eth1_41
    description: 
    ifp: LEAF101_IFP
    interface_type: switch_port
    leaf_port_block: 1
    from: 41
    to: 41
    ipg: APIC_INB_IPG
    state: present

# VPC Int Selectors 
  - name: eth1_11
    description: VPC to Cluster 2
    ifp: LEAF101-102_IFP
    interface_type: vpc
    leaf_port_block: 1
    from: 11
    to: 11
    ipg: Cluster_VPC_IPG
    state: present

  - name: eth1_26
    description: VPC to L2 Switch
    ifp: LEAF101-102_IFP
    interface_type: vpc
    leaf_port_block: 1
    from: 26
    to: 26
    ipg: L2Out_VPC_IPG
    state: present
