---
interface_profile:
  - name: LEAF101_IFP
    swp: LEAF101_SWP
    description: Interface Profile for Leaf 101
    state: present
  - name: LEAF102_IFP
    swp: LEAF102_SWP
    description: Interface Profile for Leaf 102
    state: present
  - name: LEAF101-102_IFP
    swp: LEAF101-102_SWP
    description: Leaf 101_102 vPC LEAF101_102 Interface Profile
    state: present