---
interface_policy_lldp:
  - name: LLDP_Enabled
    description: Enable LLDP on interface
    receive: true
    transmit: true
    state: present
  - name: LLDP_Disabled
    description: Disable LLDP on interface 
    receive: false
    transmit: false
    state: present
interface_policy_cdp:
  - name: CDP_Enabled
    admin_state: true
    state: present
  - name: CDP_Disabled
    admin_state: false
    state: present
interface_policy_lacp:
  - name: LACP_Active
    description: LACP Active
    min: 1
    max: 16
    mode: active
