---
vlan_pools:
  - vlan_pool_name: physical_pool
    vlan_pool_description: physical pool
    vlan_pool_mode: static
    state: present

vlan_block_ranges:
  - start: 100
    end: 1000
    vlan_pool_name: physical_pool
    state: present
    vlan_pool_mode: static
