---
vlan_pools:
  - vlan_pool_name: cluster
    vlan_pool_description: Cluster hosts vlan pool
    vlan_pool_mode: static
    state: present

  - vlan_pool_name: mgmt
    vlan_pool_description: mgmt vlan pool
    vlan_pool_mode: static
    state: present

vlan_block_ranges:
  - start: 200
    end: 299
    vlan_pool_name: cluster
    state: present
    vlan_pool_mode: static

  - start: 300
    end: 399
    vlan_pool_name: mgmt
    state: present
    vlan_pool_mode: static