---
- name: Create access policies for fabric1
  hosts: fabric1
  gather_facts: false
  connection: local
  any_errors_fatal: true
  module_defaults:
    group/cisco.aci.all:
      hostname: "{{ ansible_host }}"
      username: "{{ apic_username }}"
      password: "{{ apic_password }}"
      validate_certs: "{{ apic_validate_certs }}"
      use_proxy: "{{ apic_use_proxy }}"

  roles:
    - roles/ap_swp
    - roles/ap_ifp
    - roles/ap_int_policy
    - roles/ap_access_ipg
    - roles/ap_vpc_ipg
    - roles/ap_vpc_prot_grp
    - roles/ap_interface_selector
    - roles/ap_vlans
    - roles/ap_domains
    - roles/ap_aaep