---
# tasks file for roles/tn_l2out
# ------------------------------------
# Configure L2Out VPC on bordler leafs
# ------------------------------------
- name: Create L2Out (l2ext:Out)
  cisco.aci.aci_l2out:
    name: '{{ item.name }}'
    tenant: '{{ item.tenant }}'
    bd: "{{ item.bd }}"
    domain: '{{ item.domain }}'
    vlan: "{{ item.vlan }}"
    state: '{{ item.state }}'
  delegate_to: localhost
  when: l2out is defined
  loop: "{{ l2out }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false

- name: Create L2Out Node Profile (l2ext:LNodeP)
  cisco.aci.aci_l2out_logical_node_profile:
    tenant: '{{ item.tenant }}'
    l2out: '{{ item.l2out }}'
    node_profile: '{{ item.profile }}'
    state: '{{ item.state }}'
  delegate_to: localhost
  when: l2out_node is defined
  loop: "{{ l2out_node }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false

- name: Create an interface profile in the L2out node profile (l2ext:LIfP)
  cisco.aci.aci_l2out_logical_interface_profile:
    tenant: "{{ item.tenant }}"
    l2out: "{{ item.l2out }}"
    node_profile: "{{ item.node_profile }}"
    interface_profile: "{{ item.interface_profile }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: l2out_interface is defined
  loop: "{{ l2out_interface }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false

- name: Configure a path in the L2out interface profile (l2ext:RsPathL2OutAtt)
  cisco.aci.aci_l2out_logical_interface_path:
    tenant: '{{ item.tenant }}'
    l2out: '{{ item.l2out }}'
    node_profile: '{{ item.node_profile }}'
    interface_profile: "{{ item.interface_profile }}"
    interface_type: "{{ item.interface_type }}"
    pod_id: '{{ item.pod_id }}'
    leaves: '{{ item.leaves }}'
    interface: "{{ item.interface }}"
    state: '{{ item.state }}'
  delegate_to: localhost
  when: l2out_interface is defined
  loop: "{{ l2out_interface }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false

- name: Create L2Out EPG (l2ext:InstP)
  cisco.aci.aci_l2out_extepg:
    tenant: '{{ item.tenant }}'
    l2out: '{{ item.l2out }}'
    name: '{{ item.name }}'
    description: "{{ item.description }}"
    state: '{{ item.state }}'
  delegate_to: localhost
  when: l2_extepg is defined
  loop: "{{ l2_extepg }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false
