- name: Bind PEG to static ports (fv:RsPathAtt)
  cisco.aci.aci_static_binding_to_epg:
    tenant: "{{ item.tenant }}"
    ap: "{{ item.ap }}"
    epg: "{{ item.epg }}"
    interface_mode: "{{ item.interface_mode }}"
    interface_type: "{{ item.interface_type }}"
    pod_id: "{{ item.pod_id }}"
    leafs: "{{ item.leaf }}"
    interface: "{{ item.interface }}"
    encap_id: "{{ item.encap_id }}"
    deploy_immediacy: immediate
    description: "{{ item.description }}"
    state: "{{ item.state }}"
  delegate_to: localhost
  when: epg_bindings is defined
  loop: "{{ epg_bindings }}"
  register: result
  retries: "{{ loop_retries }}"
  delay: "{{ retry_delay }}"
  until: result.failed == false