name: Ansible Lint
on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
        

      # - name: Install yamllint
      #   run: pip install yamllint

      # - name: Lint YAML files
      #   run: |
      #     yamllint ./playbooks
      #     yamllint ./roles
      #     yamllint ./host_vars