name: Ansible Lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Ansible and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install ansible-lint==25.1.3
          ansible-galaxy collection install cisco.aci

      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
