name: Ansible Lint
on: [push, pull_request]

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        

      # - name: Install yamllint
      #   run: pip install yamllint

      # - name: Lint YAML files
      #   run: |
      #     yamllint ./playbooks
      #     yamllint ./roles
      #     yamllint ./host_vars