name: Validate and Deploy ACI Fabric
on: [push, pull_request]

jobs:
# run the ansible-lint process
  ansible-lint:
    name: Ansible Lint # Run a linting action against the repo before next step
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          setup_python: "true"

# run dry run and store the results of the pending changes in a file in each respective playbook directory
  ansible-dry-run:
    name: Ansible Dry Run
    runs-on: self-hosted
    needs: ansible-lint
    container: cmons/ansible:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible playbook dry-run
        run: |
          ansible --version
          ansible-playbook playbooks/fabric1/fabric_deploy.yml -i ACI_Hosts.yml --check

# take an ACI snapshot
  aci-snapshot:
    name: ACI Snapshot
    runs-on: self-hosted
    needs: ansible-dry-run
    container: cmons/ansible:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible playbook snapshot
        run: |
          ansible --version
          ansible-playbook playbooks/fabric1/snapshot.yml -i ACI_Hosts.yml

# deploy the ACI fabric changes using Ansible
  ansible-deploy:
    name: Ansible Deploy Fabric
    runs-on: self-hosted
    needs: aci-snapshot
    container: cmons/ansible:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible playbook Fabric Deploy
        run: |
          ansible --version
          ansible-playbook playbooks/fabric1/fabric_deploy.yml -i ACI_Hosts.yml
